name: Generate docs

on:
  schedule:
    - cron: '0 11 * * *' # 11:00 UTC, 03:00 PT, 06:00 ET
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  deploy:

    name: API docs
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Checkout develop branch
        uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Set up stubs
        run: composer run doctum:stubs

      - name: Generate API documentation
        run: ./vendor/bin/doctum.php update --force --no-ansi --no-progress --output-format=github -v doctum/config.php

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
